// 20 - React Web App -2/reactapp/src/orderDetails.tsx
import React, { Component } from "react";
import { StoreData } from "./data/types";
import { Order } from "./data/entities";
import { connect } from "react-redux";
import { NavLink } from "react-router-dom";

const mapStateToProps = (data: StoreData) => ({
    order: data.order
})

interface Props {
    order: Order,
    submitCallback: () => void    
}

const connectFunction = connect(mapStateToProps);
export const OrderDetails = connectFunction(
    class extends Component<Props> {
        render() {
            return <div>
            <h3 className="text-center bg-primary text-white p-2">Order Summary</h3>
            <div className="p-3">
                <table className="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>Quantity</th><th>Product</th>
                            <th className="text-right">Price</th>
                            <th className="text-right">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        { this.props.order.orderLines.map(line =>
                            <tr key={ line.product.id }>                            
                                <td>{ line.quantity }</td>
                                <td>{ line.product.name }</td>
                                <td className="text-right">
                                    ${ line.product.price.toFixed(2) }
                                </td>
                                <td className="text-right">
                                    ${ line.total.toFixed(2) }
                                </td>
                            </tr>
                        )}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th className="text-right" colSpan={3}>Total:</th>
                            <th className="text-right">
                                ${ this.props.order.total.toFixed(2) }
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div className="text-center">
                <NavLink to="/products" className="btn btn-secondary m-1">
                    Back
                </NavLink>
                <button className="btn btn-primary m-1" 
                        onClick={ this.props.submitCallback }>
                    Submit Order
                </button>                
            </div>
        </div>                
    }});

// 22 - Vue.js Web App - 2/vueapp/src/views/OrderDetails.vue
<template>
    <div>
        <h3 class="text-center bg-primary text-white p-2">Order Summary</h3>
        <div class="p-3">
            <table class="table table-sm table-striped">
                <thead>
                    <tr>
                        <th>Quantity</th><th>Product</th>
                        <th class="text-right">Price</th>
                        <th class="text-right">Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="line in order.lines" v-bind:key="line.product.id">                            
                        <td>{{ line.quantity }}</td>
                        <td>{{ line.product.name }}</td>
                        <td class="text-right">
                            ${{ line.product.price.toFixed(2) }}
                        </td>
                        <td class="text-right">
                            ${{ line.total.toFixed(2) }}
                        </td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th class="text-right" colSpan="3">Total:</th>
                        <th class="text-right">
                            ${{ order.total.toFixed(2) }}
                        </th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="text-center">
            <router-link to="/products" class="btn btn-secondary m-1">
                Back
            </router-link>
            <button class="btn btn-primary m-1" @click="submit">
                Submit Order
            </button>                
        </div>
    </div>          
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";
import { Order } from "../data/entities";
import { state, action } from "../data/storeDecorators";
import { HttpHandler } from '../data/httpHandler';
import router from "../router";

@Component({
    router
})
export default class OrderDetails extends Vue {
    private httpHandler = new HttpHandler();

    @state("order")
    order!: Order

    @action()
    storeOrder(task: (order: Order) => Promise<number>) {}

    submit() {
        this.storeOrder((order: Order) => {
            return this.httpHandler.storeOrder(order).then(id => {
                this.$router.push("/summary");
                return id;
            });
        });        
    }
}

</script>
