// 17 - Angular Web App/angularapp/src/app/categoryList.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
    selector: "category-list",
    templateUrl: "./categoryList.component.html"
})
export class CategegoryList {
    
    @Input()
    selected: string

    @Input()
    categories: string[];

    @Output()
    selectCategory = new EventEmitter<string>();

    getBtnClass(category: string): string {
        return  "btn btn-block " + 
            (category === this.selected ? "btn-primary" : "btn-secondary");
    }
}

<button *ngFor="let cat of categories" [class]="getBtnClass(cat)"
        (click)="selectCategory.emit(cat)">
    {{ cat }}
</button>

// 21 - Vue.js Web App/vueapp/src/components/CategoryList.vue
<template>
    <div>
        <button v-for="c in categories" 
            v-bind:key="c"
            v-bind:class="getButtonClasses(c)"
            @click="selectCategory(c)">
                {{ c }}
        </button>
    </div>     
    
</template>

<script lang="ts">

import { Component, Prop, Vue, Emit } from "vue-property-decorator";

@Component
export default class CategoryList extends Vue {

    @Prop() 
    private categories!: string[];
    
    @Prop() 
    private selected: string = this.categories[0];

    selectCategory(category: string) {
        this.$emit("selectCategory", category);
    }

    getButtonClasses(category: string) : string {
        let btnClass = this.selected === category 
            ? "btn-primary": "btn-secondary";        
        return `btn btn-block ${btnClass}`;
    }
 }

</script>
