// 20 - React Web App -2/reactapp/src/categoryList.tsx
import React, { Component } from "react";

interface Props {
    selected: string,
    categories: string[],
    selectCategory: (category: string) => void;
}

export class CategoryList extends Component<Props> {

    render() {
        return <div>
            { ["All", ...this.props.categories].map(c => {
                let btnClass = this.props.selected === c 
                    ? "btn-primary": "btn-secondary";
                return <button key={ c }
                        className={ `btn btn-block ${btnClass}` } 
                        onClick={ () => this.props.selectCategory(c) }>
                    { c }
                </button>            
            }) }
        </div>     
    }
}

// 21 - Vue.js Web App/vueapp/src/components/CategoryList.vue
<template>
    <div>
        <button v-for="c in categories" 
            v-bind:key="c"
            v-bind:class="getButtonClasses(c)"
            @click="selectCategory(c)">
                {{ c }}
        </button>
    </div>     
    
</template>

<script lang="ts">

import { Component, Prop, Vue, Emit } from "vue-property-decorator";

@Component
export default class CategoryList extends Vue {

    @Prop() 
    private categories!: string[];
    
    @Prop() 
    private selected: string = this.categories[0];

    selectCategory(category: string) {
        this.$emit("selectCategory", category);
    }

    getButtonClasses(category: string) : string {
        let btnClass = this.selected === category 
            ? "btn-primary": "btn-secondary";        
        return `btn btn-block ${btnClass}`;
    }
 }

</script>
