// 16 - Stand-Alone Web App - 2/webapp/src/orderDetails.tsx
import { createElement } from "./tools/jsxFactory";
import { Product, Order } from "./data/entities";

export class OrderDetails {

    props: {
        order: Order
        cancelCallback: () => void,
        submitCallback: () => void
    }

    getContent(): HTMLElement {
        return <div>
            <h3 className="text-center bg-primary text-white p-2">
                Order Summary
            </h3>
            <div className="p-3">
                <table className="table table-sm table-striped">
                    <thead>
                        <tr>
                            <th>Quantity</th><th>Product</th>
                            <th className="text-right">Price</th>
                            <th className="text-right">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        { this.props.order.orderLines.map(line =>
                            <tr>
                                <td>{ line.quantity }</td>
                                <td>{ line.product.name }</td>
                                <td className="text-right">
                                    ${ line.product.price.toFixed(2) }
                                </td>
                                <td className="text-right">
                                    ${ line.total.toFixed(2) }
                                </td>
                            </tr>
                        )}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th className="text-right" colSpan="3">Total:</th>
                            <th className="text-right">
                                ${ this.props.order.total.toFixed(2) }
                            </th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div className="text-center">
                <button className="btn btn-secondary m-1" 
                        onclick={ this.props.cancelCallback }>
                    Back
                </button>
                <button className="btn btn-primary m-1" 
                        onclick={ this.props.submitCallback }>
                    Submit Order
                </button>                
            </div>
        </div>       
    }
}

// 18 - Angular Web App - 2/angularapp/src/app/orderDetails.component.ts
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { Order } from "./data/entities";
import { DataSource } from './data/dataSource';

@Component({
    selector: "order-details", 
    templateUrl: "./orderDetails.component.html"
})
export class OrderDetails {

    constructor(private dataSource: DataSource, private router: Router) {}

    get order() : Order {
        return this.dataSource.order;
    }
    
    submit() {
        this.dataSource.storeOrder().subscribe(id => 
            this.router.navigateByUrl(`/summary/${id}`));
    } 
}

<h3 class="text-center bg-primary text-white p-2">Order Summary</h3>
<div class="p-3">
    <table class="table table-sm table-striped">
        <thead>
            <tr>
                <th>Quantity</th><th>Product</th>
                <th class="text-right">Price</th>
                <th class="text-right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let line of order.orderLines">
                    <td>{{ line.quantity }}</td>
                    <td>{{ line.product.name }}</td>
                    <td class="text-right">${{ line.product.price.toFixed(2) }}</td>
                    <td class="text-right">${{ line.total.toFixed(2) }}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <th class="text-right" colSpan="3">Total:</th>
                <th class="text-right">
                    ${{ order.total.toFixed(2) }}
                </th>
            </tr>
        </tfoot>
    </table>
</div>
<div class="text-center">
    <button class="btn btn-secondary m-1" routerLink="/products">Back</button>
    <button class="btn btn-primary m-1" (click)="submit()">Submit Order</button>                
</div>
