// 21 - Vue.js Web App/vueapp/src/components/Header.vue
<template>
            
    <div class="p-1 bg-secondary text-white text-right">
        {{ displayText }} 
        <button class="btn btn-sm btn-primary m-1">
            Submit Order
        </button>
    </div>

</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";
import { Order } from "../data/entities";
import { state } from "../data/storeDecorators";

@Component
export default class Header extends Vue {

    @state("order")
    order!: Order

    get displayText() : string {
        let count = this.order.productCount;
        return count === 0 ? "(No Selection)" 
            : `${ count } product(s), $${ this.order.total.toFixed(2)}`
    }
}

</script>

// 16 - Stand-Alone Web App - 2/webapp/src/header.tsx
import { createElement } from "./tools/jsxFactory";
import { Order } from "./data/entities";

export class Header {

    props: {
        order: Order,
        submitCallback: () => void
    }

    getContent(): HTMLElement {
        let count = this.props.order.productCount;
        return <div className="p-1 bg-secondary text-white text-right">
            { count === 0 ? "(No Selection)" 
                : `${ count } product(s), $${ this.props.order.total.toFixed(2)}` }
            <button className="btn btn-sm btn-primary m-1" 
                    onclick={ this.props.submitCallback }>
                Submit Order
            </button>
        </div>
    }
}
