// 21 - Vue.js Web App/vueapp/src/views/ProductList.vue
<template>
    <div>
        <Header />
        <div class="container-fluid">
            <div class="row">
                <div class="col-3 p-2">
                    <CategoryList v-bind:categories="categories" 
                        v-bind:selected="selectedCategory"
                        @selectCategory="handleSelectCategory" />
                </div>
                <div class="col-9 p-2">
                    <ProductItem v-for="p in filteredProducts" v-bind:key="p.id"  
                        v-bind:product="p" @addToCart="handleAddToCart" />
                </div>                            
            </div>        
        </div>
    </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";
import { Product, Order } from "../data/entities";
import ProductItem from "../components/ProductItem.vue";
import CategoryList from "../components/CategoryList.vue";
import Header from "../components/Header.vue";
import { state, getter, mutation } from "../data/storeDecorators";

@Component({
    components: {
        ProductItem, CategoryList, Header
    }
})
export default class ProductList extends Vue {
    
    @state("selectedCategory")
    selectedCategory!: string;

    @getter()
    filteredProducts!: Product[];

    @getter()
    categories!: string[]

    @mutation("selectCategory")
    handleSelectCategory(category: string) {}

    @mutation("addToOrder")
    handleAddToCart(selection: { product: Product, quantity: number}) {}
}

</script>

// 15 - Stand-Alone Web App/webapp/src/productList.tsx
import { createElement } from "./tools/jsxFactory";
import { Product } from "./data/entities";
import { ProductItem } from "./productItem";
import { CategoryList } from "./categoryList";

export class ProductList {
    props: {
        products: Product[],
        categories: string[],
        selectedCategory: string,
        addToOrderCallback?: (product: Product, quantity: number) => void,
        filterCallback?: (category: string) => void;
    }

    getContent(): HTMLElement {
        return <div className="container-fluid">
            <div className="row">
                <div className="col-3 p-2">
                    <CategoryList categories={ this.props.categories } 
                        selectedCategory={ this.props.selectedCategory }
                        callback={ this.props.filterCallback } />
                </div>
                <div className="col-9 p-2">
                    {
                        this.props.products.map(p => 
                            <ProductItem product={ p } 
                                callback={ this.props.addToOrderCallback } />)
                    }
                </div>                            
            </div>
        </div>
    }
}
