// 21 - Vue.js Web App/vueapp/src/views/ProductList.vue
<template>
    <div>
        <Header />
        <div class="container-fluid">
            <div class="row">
                <div class="col-3 p-2">
                    <CategoryList v-bind:categories="categories" 
                        v-bind:selected="selectedCategory"
                        @selectCategory="handleSelectCategory" />
                </div>
                <div class="col-9 p-2">
                    <ProductItem v-for="p in filteredProducts" v-bind:key="p.id"  
                        v-bind:product="p" @addToCart="handleAddToCart" />
                </div>                            
            </div>        
        </div>
    </div>
</template>

<script lang="ts">

import { Component, Prop, Vue } from "vue-property-decorator";
import { Product, Order } from "../data/entities";
import ProductItem from "../components/ProductItem.vue";
import CategoryList from "../components/CategoryList.vue";
import Header from "../components/Header.vue";
import { state, getter, mutation } from "../data/storeDecorators";

@Component({
    components: {
        ProductItem, CategoryList, Header
    }
})
export default class ProductList extends Vue {
    
    @state("selectedCategory")
    selectedCategory!: string;

    @getter()
    filteredProducts!: Product[];

    @getter()
    categories!: string[]

    @mutation("selectCategory")
    handleSelectCategory(category: string) {}

    @mutation("addToOrder")
    handleAddToCart(selection: { product: Product, quantity: number}) {}
}

</script>

// 20 - React Web App -2/reactapp/src/productList.tsx
import React, { Component } from "react";
import { Header } from "./header";
import { ProductItem } from "./productItem";
import { CategoryList} from "./categoryList";
import { Product, Order } from "./data/entities";

interface Props {
    products: Product[],
    categories: string[],
    order: Order,
    addToOrder: (product: Product, quantity: number) => void
}

interface State {
    selectedCategory: string;
}

export class ProductList extends Component<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            selectedCategory: "All"
        }
    }

    render() {
        return <div>
            <Header order={ this.props.order } />
            <div className="container-fluid">
                <div className="row">
                    <div className="col-3 p-2">
                        <CategoryList categories={ this.props.categories } 
                            selected={ this.state.selectedCategory }
                            selectCategory={ this.selectCategory } />
                    </div>
                    <div className="col-9 p-2">
                        {
                            this.products.map(p => 
                                <ProductItem key={ p.id } product={ p } 
                                    callback={ this.props.addToOrder } />)
                        }
                    </div>                            
                </div>
            </div>
        </div>
    }

    get products(): Product[] {
        return this.props.products.filter(p => this.state.selectedCategory === "All" 
            || p.category === this.state.selectedCategory);
    }

    selectCategory = (cat: string) => {
        this.setState({ selectedCategory: cat});
    }
}
